name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Install node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Run Sonar
        run: |
          npm install 
          npm run sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}   # Generate a token on SonarQube, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST_URL }}   # add the URL of your instance to the secrets of this repo with the name SONAR_HOST_URL (Settings > Secrets > Actions > add new repository secret)
      - name: docker login
        env:
          DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
          DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USER}}/rsa-nodejs:latest
      - name: Docker Push
        run: docker push ${{secrets.DOCKERHUB_USER}}/rsa-nodejs:latest
        
 
